branch-defaults:
  default:
    environment: image-filter-starter-code-dev
    group_suffix: null
  main:
    environment: image-filter-starter-code-dev
global:
  application_name: image-filter-starter-code
  branch: null
  default_ec2_keyname: goetz
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application