branch-defaults:
  development:
    environment: image-filter-bong011-dev
    group_suffix: null
global:
  application_name: image-filter-bong011
  branch: null
  default_ec2_keyname: Ireland-goetz
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
